---
  version: '3'
  services:
    web:
      container_name: 'jakal-app'
      environment:
        - PORT=8085
        - DB_HOST=mongo-bongo
        - PERIOD_SUGGEST_START_DAY=9
        - PERIOD_VOTING_START_DAY=10
        - PERIOD_DISPLAY_START_DAY=15
      build: .
      ports:
        - 3100:8085
      links:
        - mongo
    mongo:
      container_name: 'mongo-bongo'
      image: mongo
